### ISSUE TITLE
RxSwift Examples Checklist

### ISSUE THREAD

**Issue by at-daonguyen** [blkbrds/sample-rxswift#16]
**View**
- [ ] Data Binding
  - [ ] Simple UI.
  - [ ] Cell Data Binding
  - [ ] Multiple Cell Type
  - [ ] MapView
- [ ] Input Adapter
  - [ ] Form
  - [ ] Input Transform
  - [ ] Input Validation
  - [ ] Search
- [ ] Chaining Alerts/Popups

**API**
- [ ] Normal Request with Alamofire
- [ ] Cancelable Request
- [ ] [Moya](https://github.com/Moya/Moya) Integration

**Comment by at-daonguyen** [comment]
@at-vietha Em có update gì cái Chẹclist này ko hè?

**Comment by at-daonguyen** [comment]
@at-vietha Em có update gì cái Checklist này ko hè? Sao không khác gì lúc anh tạo ri...

**Comment by at-tienhuynh** [comment]
@at-daonguyen I updated In a general manner. But with our team, we will be follow basic parts! With Extensions, we will be implement if we can do!

**Comment by at-daonguyen** [comment]
@at-tienhuynh Ghi tiếng Việt đi pa, tại sao `Extensions` lại nằm trong `View`?

**Comment by at-tienhuynh** [comment]
@at-daonguyen  đã sửa :D

**Comment by at-daonguyen** [comment]
@at-tienhuynh
- #23 quá chung chung.
- #32, #33 nên move vào `Model` section.
- #34 ~ #29.

**Comment by at-daonguyen** [comment]
@at-haiphung Có thêm bớt gì ko anh?

**Comment by at-tienhuynh** [comment]
@at-daonguyen Đã new sửa :D

**Comment by at-haiphung** [comment]
@at-daonguyen ok rồi, tks @at-tienhuynh updated dùm!

**Comment by at-daonguyen** [comment]
Ko thấy assignee trong các issue hè? Ai làm task nào vô tự assign nha @at-vietha @at-haiphung @at-hieutran @at-tienhuynh.
